### PR TITLE
new examples for basics

### PR DESCRIPTION
**Pull request by mmann1123**
Just added your example notebook and another one going over mosaics, band math, and masking.

Although it appears to work (although please see that ndvi <= -0.25 still plots on the range [-0.6,0.6]), can you check that this is how you want people to do masking?   

Also I was wondering how we would apply the NDVI across the RBG bands. Might be something to add later.

### CODE REVIEW

**Comment by jgrss** [comment]
I am not sure why Xarray doesn't recalculate the range after masking. But, if you do:

```python
masker.sel(band='ndvi').gw.imshow(robust=True) 
```

then it plots from the 90th and 10th percentiles.

**Comment by jgrss** [comment]
For masking, Xarray supports conversion to nans for DataArrays. For example, I think that

```python
masker = ndvi >= -0.25
```

does the same thing as:

```python
masker = ndvi.where(ndvi >= -0.25)
```

**Comment by jgrss** [comment]
I am not sure I understand what you mean by:

> Also I was wondering how we would apply the NDVI across the RBG bands. Might be something to add later.

**Comment by mmann1123** [comment]
> > Also I was wondering how we would apply the NDVI across the RBG bands. Might be something to add later.

I meant, it would be good to be able to mask RGB bands with the same mask, for instance one based on NDVI. Let me know if you have that figured out already, but I will play around and see if I can figure it out.

**Pull request merged**
