### PR TITLE
v2.1.6 bug fixes

### PR DESCRIPTION
**Pull request by jgrss**
## What is this PR changing?
This PR addresses:
* #249 merged in #250
* `pyproj>3.4.0` WKT errors addressed in #254 
* CONTRIBUTING.md guide from #253 
* New docs theme from #256 
* Added test coverage in #255

### CODE REVIEW

**Comment by jgrss** [comment]
This is a side tracking PR and NOT YET ready for view.

**Comment by jgrss** [comment]
@mmann1123 the entirety of this PR has already been reviewed with the exception of the last commit.

**Comment by mmann1123** [comment]
Ok submit a review request or force the merge

**Comment by jgrss** [comment]
> Ok submit a review request or force the merge

We're passing on CI now.

**Pull request merged**
