### PR TITLE
old _filenames attribute reference

### PR DESCRIPTION
**Pull request by mmann1123**
Was trying to run to_vrt when I noticed this _filenames call. I am 99% its old

### CODE REVIEW

**Comment by mmann1123** [comment]
I am also assuming that 
```
@filenames.setter
def filenames(self, file_list):
        self._filenames = file_list
```

should be 

```
@filenames.setter
 def filenames(self, file_list):
        self.filename = file_list
```

But not sure

**Comment by jgrss** [comment]
Hmm, this was intentional. Did you receive an error?

```python
@property
def filenames(self):
    """Get the data filenames"""
    return self._filenames if hasattr(self, '_filenames') else []

@filenames.setter
def filenames(self, file_list):
    self._filenames = file_list
```

**Comment by jgrss** [comment]
For reference, in [api.py](https://github.com/jgrss/geowombat/blob/master/geowombat/core/api.py), the `filenames` property gets set if the opened files are given as a list. See here:

```python
def __enter__(self):
    self.__is_context_manager = True
    self.data.gw.filenames = self.__filenames
    self.data.gw.data_are_separate = self.__data_are_separate
    return self.data
```

The lingering issue might be that `to_vrt()` only works with a single file (e.g., to quickly warp an image and save it).

**Comment by mmann1123** [comment]
I guess the issue for me is that ds.filenames always returns []. Unless I
am missing something.

**Comment by jgrss** [comment]
Sorry, my fault. `filename` is an `xarray.DataArray` attribute, whereas `filenames` is an `xarray.DataArray.gw` property. Aside from how they are nested, the main difference is that `gw.filenames` stores the full path to the files. 

I was also wrong in telling you that `to_vrt()` only accepts a single file. The `gw.filenames` property is used to create a VRT with GDAL when multiple files are opened. 

### With a single file

```python
import geowombat as gw
from geowombat.data import l8_224077_20200518_B2

with gw.open(l8_224077_20200518_B2) as src:
    print(src.filename)
    print(src.gw.filenames)

../envs/ts3.7/lib/python3.7/site-packages/geowombat/data/LC08_L1TP_224077_20200518_20200518_01_RT_B2.TIF
['../envs/ts3.7/lib/python3.7/site-packages/geowombat/data/LC08_L1TP_224077_20200518_20200518_01_RT_B2.TIF']
```

### With multiple files

```python
with gw.open([l8_224077_20200518_B2, l8_224077_20200518_B2]) as src:
    print(src.filename)
    print(src.gw.filenames)

['LC08_L1TP_224077_20200518_20200518_01_RT_B2.TIF', 'LC08_L1TP_224077_20200518_20200518_01_RT_B2.TIF']
['../envs/ts3.7/lib/python3.7/site-packages/geowombat/data/LC08_L1TP_224077_20200518_20200518_01_RT_B2.TIF', '../envs/ts3.7/lib/python3.7/site-packages/geowombat/data/LC08_L1TP_224077_20200518_20200518_01_RT_B2.TIF']
```

**Comment by mmann1123** [comment]
Cool thanks for following up.

**Comment by jgrss** [comment]
I am closing this for now, but feel free to reopen.

**Pull request closed without merging**
