### PR TITLE
Mmann1123 conda

### PR DESCRIPTION
**Pull request by mmann1123**
## What is this PR changing?
adding conda install 
I think I added the docs: tag?? Never done this before, so let me know if this was not right. 
  
### Checklist
- [ x] Remember to add a semantic tag to the commit name

### CODE REVIEW

**Review by jgrss — APPROVED** [review]
Don't worry about that CI test failure. I've been meaning to remove it since we're now using GitHub CI.

**Comment by jgrss** [comment]
@mmann1123 let me know if you are  unable to merge this because Circle is blocking it.

**Comment by jgrss** [comment]
Re: docs: tag, I think it should be fine. I typically don't include it in the commit messages. What I would do is, now after an approved PR, select `Squash and merge` and in the final merge message write something like `docs: Mmann1123 conda`. Since you have it in a commit message then don't include a tag in the merge message on this PR. Anyway, `docs:` won't trigger any version changes.

**Comment by mmann1123** [comment]
Well I squashed and merged on the app from my phone. Didn't prompt for another message. Hopefully the tag and commit do the trick?

**Pull request merged**
