### PR TITLE
Jgrss/docker

### PR DESCRIPTION
**Pull request by mmann1123**
## What is this PR changing?
adding python-is-python3 so `python whatever` works. 

I think this looks good and passes all tests. I would post it.

### CODE REVIEW

**Comment by jgrss** [comment]
@mmann1123 when did you pull from `main`? Just curious because PR `[5bc07aa](https://github.com/jgrss/geowombat/pull/155/commits/5bc07aa361876faa1c8f3c7165bd7aa4f19969fa) with the `requests` upgrade broke CI. You should no longer see the requests versions in the commit message (that's what broke things).

**Comment by jgrss** [comment]
Ohh, I see. Let me pull your additions and test `semantic-release` locally.

Also, what is `python-is-python3`? When I run that image it installs Python 3.8. Does `python-is-python3` install something else?

**Comment by mmann1123** [comment]
My understanding is that it creates a link from python3 to python so they
can both be used from the command line.

**Review by jgrss — APPROVED** [review]

**Comment by mmann1123** [comment]
Yeah just read up on it. It's just a symlink between python call and path
to python3.

**Pull request merged**
