### PR TITLE
jgrss/#242

### PR DESCRIPTION
**Pull request by jgrss**
## What is this PR changing?
Following #242, this changes `Path.rename` to `Path.replace` in order to handle files in Windows.

### CODE REVIEW

**Review by mmann1123 — APPROVED** [review]

**Comment by jgrss** [comment]
@mmann1123 Can you do one more quick look? I added a test and deprecated an inconsistent argument.

**Comment by mmann1123** [comment]
@jgrss sure give me a bit

**Comment by mmann1123** [comment]
I am getting an error on coreg... but might have to do with my build.

```
======================================================================
ERROR: test_coreg_data (test_coreg.TestCOREG)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/geowombat/tests/test_coreg.py", line 29, in test_coreg_data
    data = gw.coregister(
  File "/geowombat/src/geowombat/core/sops.py", line 1230, in coregister
    raise NameError
NameError

======================================================================
ERROR: test_coreg_shift (test_coreg.TestCOREG)
Tests a 1-pixel shift.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/geowombat/tests/test_coreg.py", line 79, in test_coreg_shift
    shifted = gw.coregister(
  File "/geowombat/src/geowombat/core/sops.py", line 1230, in coregister
    raise NameError
NameError

======================================================================
ERROR: test_coreg_transform_data (test_coreg.TestCOREG)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/geowombat/tests/test_coreg.py", line 50, in test_coreg_transform_data
    data = gw.coregister(
  File "/geowombat/src/geowombat/core/sops.py", line 1230, in coregister
    raise NameError
NameError

----------------------------------------------------------------------
Ran 88 tests in 20.577s
FAILED (errors=3)
```

**Comment by jgrss** [comment]
> I am getting an error on coreg... but might have to do with my build.
> 
> ```
> ======================================================================
> ERROR: test_coreg_data (test_coreg.TestCOREG)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/geowombat/tests/test_coreg.py", line 29, in test_coreg_data
>     data = gw.coregister(
>   File "/geowombat/src/geowombat/core/sops.py", line 1230, in coregister
>     raise NameError
> NameError
> 
> ======================================================================
> ERROR: test_coreg_shift (test_coreg.TestCOREG)
> Tests a 1-pixel shift.
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/geowombat/tests/test_coreg.py", line 79, in test_coreg_shift
>     shifted = gw.coregister(
>   File "/geowombat/src/geowombat/core/sops.py", line 1230, in coregister
>     raise NameError
> NameError
> 
> ======================================================================
> ERROR: test_coreg_transform_data (test_coreg.TestCOREG)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/geowombat/tests/test_coreg.py", line 50, in test_coreg_transform_data
>     data = gw.coregister(
>   File "/geowombat/src/geowombat/core/sops.py", line 1230, in coregister
>     raise NameError
> NameError
> 
> ----------------------------------------------------------------------
> Ran 88 tests in 20.577s
> FAILED (errors=3)
> ```

Hmm, was that a new build? All tests just passed on this PR branch.

**Comment by mmann1123** [comment]
@jgrss I think its just an issue with how I did the dockerfile.

**Pull request merged**
